:repository-owner: BloomyControls
:repository-name: BloomyEthernet

= {repository-name} Library for Arduino =

This is a fork of the official Arduino Ethernet library. This fork makes minor
tweaks to fix a few bugs. It also changes the Ethernet library interface such
that the user specifies the SPI bus and chip select to use, allowing multiple
instances or more control in general. The tweaks also make it more thread safe
and avoid globals, meaning that multi-core devices may use multiple instances to
control multiple Ethernet controllers safely.

This fork is NOT intended to contribute upstream. It is not compatible with the
official Ethernet library, so when you include BloomyEthernet.h, you must not
also include Ethernet.h!

== License ==

Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
